<?php
/**
 * Implements hook_schema().
 */
function aten_dev_content_schema() {
  return [
    'development_content_map' => [
      'fields' => [
        'machine_name' => [
          'type' => 'varchar',
          'length' => 128,
          'not null' => TRUE,
        ],
        'entity' => [
          'type' => 'varchar',
          'length' => 255,
          'not null' => TRUE,
        ],
        'entity_id' => [
          'type' => 'int',
          'unsigned' => TRUE,
          'not null' => TRUE,
        ],
        'bundle' => [
          'type' => 'varchar',
          'length' => 255,
          'not null' => TRUE,
          'default' => '',
        ],
        'hash' => [
          'type' => 'varchar',
          'length' => 255,
          'not null' => TRUE,
        ],
        'source' => [
          'type' => 'varchar',
          'length' => 255,
          'not null' => TRUE,
        ],
        'module' => [
          'type' => 'varchar',
          'length' => 128,
          'not null' => TRUE,
        ],
      ],
      'primary key' => ['module', 'machine_name'],
    ],
  ];
}
